### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-191-dremliuk#1]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
4) Відомо, що з серпня 2021 року GitHub-сервер замінив класичний процес 
аутентифікації через пароль на процес з використанням Token 
під час безпечного оновлення GitHub-репозиторію. 
Поясніть, будь ласка, чому так було зроблено?

**Comment by Daves8** [comment]
Перш за все задля забезпечення безпеки, так як паролі можуть бути скомпрометованими, а оновлення за допомогою токену може підтвердити що саме користувач який є власником токену оновив репозиторій.
Також використання токену є зручним, оскільки не треба запам'ятовувати паролі. 
При створенні токену можна також вказати обмеження на дії, які можна робити у GitHub, це забезпечує безпечну роботу з репозиторіями, так як для виконання певних дій, пов'язаних з великим ризиком (як наприклад видалення репозиторію) можуть знадобитись додаткові підтвердження.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
